In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [69]:
df = pd.read_csv('IMDB Dataset.csv')

In [70]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [71]:
df.sample()

review sentiment
250  Supposedly a "social commentary" on racism and...  negative

In [72]:
df.shape

(50000, 2)

In [73]:
df.dtypes


review       object
sentiment    object
dtype: object

In [74]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [75]:
df=df.sample(5000)

In [76]:
df.shape

(5000, 2)

In [77]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [78]:
df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)

In [79]:
df.head()

review  sentiment
26000  As a another reviewer states Hanna's War is an...          1
40499  MGM tried pairing up and coming young men with...          0
9199   I don't know if I'd consider it a masterpiece ...          1
29725  This film may be great, but it is a complete r...          0
1207   This episode of Buffy was one of my personal f...          1

In [80]:
import re
clean = re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

'I don\'t know if I\'d consider it a masterpiece of not, but it\'s damn near close; it\'s extremely well made, artistic, suspenseful, intricately plotted, thematically challenging and full of bleak foreshadowing and sexual-religious imagery. There\'s also some great camera-work from Jan de Bont, an atmospheric score from Loek Dikker and outstanding acting from Jeroen Krabbé and Renée Soutendijk, the latter giving one of the most sneaky, subtle \'femme fatale\' performance I\'ve ever seen. Like many other European movies, this movie has an unashamed, non-judgmental attitude toward sex, nudity and the complexities of sexuality and has zero reservations about mixing it all up with religious and/or surrealistic (some would say blasphemous) images. In other words, if you can\'t bear the thought of seeing a lust-driven homosexual envisioning the object of his carnal desire as Jesus crucified on the cross before the two of them go at it inside a cemetery crypt then this might not be the movie

In [81]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [82]:
df['review']=df['review'].apply(clean_html)

In [83]:
def covert_lower(text):
    return text.lower()

In [84]:
df['review']=df['review'].apply(covert_lower)

In [85]:
def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [86]:
remove_special('To add scientific notation {a way of writing numbers that allows you to write only as many digits `of specificity` as you would like} you can write 7.7 * 10 ^ 2 m3 of kerosene 1.204 * 10 ^ 3 m3 of O2 and 3.3 * 10 ^ 7 newtons.')

'To add scientific notation  a way of writing numbers that allows you to write only as many digits  of specificity  as you would like  you can write 7 7   10   2 m3 of kerosene 1 204   10   3 m3 of O2 and 3 3   10   7 newtons '

In [87]:
df['review']=df['review'].apply(remove_special)

In [88]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vk394\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [89]:
from nltk.corpus import stopwords


In [90]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [91]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [92]:
df['review']=df['review'].apply(remove_stopwords)

In [93]:
df

review  sentiment
26000  [another, reviewer, states, hanna, war, outsta...          1
40499  [mgm, tried, pairing, coming, young, men, divi...          0
9199   [know, consider, masterpiece, damn, near, clos...          1
29725  [film, may, great, complete, ripoff, bill, for...          0
1207   [episode, buffy, one, personal, favorites, als...          1
...                                                  ...        ...
49970  [movie, total, dog, found, straining, find, an...          0
39298  [kids, teenagers, springwood, ohio, dead, expe...          1
4056   [hard, believe, negative, comments, regarding,...          1
38455  [well, movie, actually, one, redeeming, qualit...          0
14832  [six, students, convent, unthinkable, kill, nu...          0

[5000 rows x 2 columns]

In [94]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [95]:
y=[]
def steam_word(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [96]:
steam_word(['i','play','playing','it'])

['i', 'play', 'play', 'it']

In [97]:
df['review']=df['review'].apply(steam_word)

In [98]:
#join back
def join_back(list_input):
    return " ".join(list_input)

In [99]:
df['review']=df['review'].apply(join_back)

In [100]:
df['review']

26000    anoth review state hanna war outstand film out...
40499    mgm tri pair come young men divin one give exp...
9199     know consid masterpiec damn near close extrem ...
29725    film may great complet ripoff bill forsyth com...
1207     episod buffi one person favorit also number th...
                               ...                        
49970    movi total dog found strain find anyth laugh f...
39298    kid teenag springwood ohio dead expect one tee...
4056     hard believ neg comment regard star flick laug...
38455    well movi actual one redeem qualiti made funni...
14832    six student convent unthink kill nun overbear ...
Name: review, Length: 5000, dtype: object

In [101]:
X=df.iloc[:,0:1].values

In [102]:
X.shape

(5000, 1)

In [103]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=500)

In [104]:
X= cv.fit_transform(df['review']).toarray()

In [105]:
X.shape

(5000, 500)

In [106]:
# X[0]

In [107]:
X[0].max()

2

In [108]:
Y=df.iloc[:,-1].values

In [109]:
Y.shape

(5000,)

In [110]:
Y[7]

1

In [111]:
X[0]

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [112]:
# now train your model

In [113]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.2)

In [114]:
X_train.shape

(4000, 500)

In [115]:
X_train[0]

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [116]:
X_test.shape

(1000, 500)

In [117]:
X_test[0]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,

In [118]:
Y_train.shape

(4000,)

In [119]:
Y_train[0]

0

In [120]:
Y_test.shape

(1000,)

In [121]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [122]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [123]:
clf1.fit(X_train,Y_train)
clf2.fit(X_train,Y_train)
clf3.fit(X_train,Y_train)

BernoulliNB()

In [124]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [125]:
dm = pd.read_csv('convert_to_numpy.csv')

In [126]:
dm.shape

(49, 500)

In [127]:
# dm=dm.iloc[:,0:1].values

In [128]:
# arry = dm.to_numpy()

In [129]:
# t = [[0, 9, 5, 1, 2]]

In [130]:
Y_test.shape

(1000,)

In [131]:
y_pred1.shape

(1000,)

In [132]:
y1 = clf1.predict(dm)
print(y1)

[0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 1 1 1 0 0 0]


C:\Users\vk394\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [133]:
from sklearn.metrics import accuracy_score

In [134]:
print("GaussianNB",accuracy_score(Y_test,y_pred1))
print("MultinomialNB",accuracy_score(Y_test,y_pred2))
print("BernoulliNB",accuracy_score(Y_test,y_pred3))

GaussianNB 0.788
MultinomialNB 0.829
BernoulliNB 0.835
